In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv("../data/sampregdata.csv")

df.head()

   Unnamed: 0         x1        x2         x3         x4          y
0           1   7.331693  9.660958  -2.981869   5.214284  -2.311878
1           2  16.888609  9.546231  18.440459  11.804018   0.994307
2           3   8.280643  6.442062  -0.225791   6.493211  -5.253876
3           4   3.827778  3.741506  -2.850664  -0.226420  20.056798
4           5   9.675971  4.385008   8.344576   5.979043   9.577914

In [3]:
X_columns = ["x1", "x2", "x3", "x4"]
y = df["y"]

results = {}

for column in X_columns:
    X = df[[column]]

    model = LinearRegression()
    model.fit(X, y)

    predictions = model.predict(X)
    r2 = r2_score(y, predictions)

    results[column] = r2

results

{'x1': 2.7390559185547225e-05,
 'x2': 0.22199651344949267,
 'x3': 0.18686509840584542,
 'x4': 0.27498888457029635}

In [4]:
results_df = pd.DataFrame(
    list(results.items()),
    columns=["X Variable", "R²"]
).sort_values("R²", ascending=False)

results_df

  X Variable        R²
3         x4  0.274989
1         x2  0.221997
2         x3  0.186865
0         x1  0.000027

In [5]:
X = df[["x4"]]
y = df["y"]

model_v1 = LinearRegression()
model_v1.fit(X, y)

print("Intercept:", model_v1.intercept_)
print("Coefficient:", model_v1.coef_[0])
print("R²:", model_v1.score(X, y))

Intercept: 8.750705153951532
Coefficient: -1.2244566401591543
R²: 0.27498888457029635

In [7]:
import joblib

joblib.dump(model_v1, "../models/model_v1.pkl")

['../models/model_v1.pkl']

In [8]:
X = df[["x4", "x2"]]
y = df["y"]

model_v2 = LinearRegression()
model_v2.fit(X, y)

print("Intercept:", model_v2.intercept_)
print("Coefficients:", model_v2.coef_)
print("R²:", model_v2.score(X, y))

Intercept: 15.745003662592314
Coefficients: [-1.26146834 -0.84009006]
R²: 0.5135537867830378

In [9]:
joblib.dump(model_v2, "../models/model_v2.pkl")

['../models/model_v2.pkl']